#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  rm -f /usr/share/applications/svent-*.desktop
  rm -f /usr/share/desktop-directories/svent.directory
  rm -f /usr/share/desktop-directories/svent-*.directory
  rm -f /etc/xdg/menus/applications-merged/svent-tools.menu
fi

if [ "$1" = "purge" ]; then
  rmdir /usr/share/svent/catalog.d 2>/dev/null || true
  rmdir /usr/share/svent 2>/dev/null || true
fi

#DEBHELPER#
